require('core.plugins')
-- require('utils.functions')
require('core.settings')

require('plugins.fern')
require('plugins.ddc')
require('plugins.tagbar')
require('plugins.telescope')
require('plugins.vim-gitgutter')
require('plugins.github-copilot')
require('plugins.copilot-chat')
-- require('plugins.nvim-dap')
require('plugins.none-ls')
-- require('plugins.avante')
require('plugins.tcomment')

require('core.keymaps')
